# Not FPs.
false_positives:
  ignore:
    - rule: "INDICATOR_EXE_Packed_ASPack"
    - rule: "INDICATOR_EXE_Packed_MPress"
    - rule: "INDICATOR_EXE_Packed_VMProtect"
    - rule: "INDICATOR_SUSPICIOUS_Stomped_PECompilation_Timestamp_InTheFuture"
    - rule: "INDICATOR_EXE_Packed_SmartAssembly"
    - rule: "INDICATOR_EXE_Packed_Dotfuscator"
    - rule: "INDICATOR_SUSPICIOUS_EXE_Reversed"
    - rule: "INDICATOR_KB_CERT_43bb437d609866286dd839e1d00309f5"
    - rule: "INDICATOR_RTF_EXPLOIT_CVE_2017_11882_1"
    - rule: "INDICATOR_RTF_EXPLOIT_CVE_2017_11882_3"
    - rule: "INDICATOR_RTF_EXPLOIT_CVE_2017_11882_4"

files:
  accept:
    - "yara/*.yar"
