# Not FPs.
false_positives:
  ignore:
    - rule: "INDICATOR_EXE_Packed_ASPack"
    - rule: "INDICATOR_EXE_Packed_MPress"
    - rule: "INDICATOR_EXE_Packed_VMProtect"
    - rule: "INDICATOR_SUSPICIOUS_Stomped_PECompilation_Timestamp_InTheFuture"
    - rule: "INDICATOR_EXE_Packed_SmartAssembly"

files:
  accept:
    - "yara/*.yar"
